### ISSUE TITLE
Document the purpose of the Test Scripts

### ISSUE THREAD

**Issue by kouroshD** [uoft-cs-robotics/robot_system_tools#11]
currently in https://github.com/pairlab/franka_arm_infra/tree/922c66fd411ea4063c3c8a62b809810a11cde7dc/calibration/scripts_for_test,  there are a few scripts that their purpose might not be clear for a general reader. We have to add the purpose of their use case, either in files or better in a read me.

**Comment by Ruthrash** [comment]
documentation has been added to [https://github.com/uoft-cs-robotics/robot_system_tools/blob/master/robot_toolkit/docs/README.md](https://github.com/uoft-cs-robotics/robot_system_tools/blob/master/robot_toolkit/docs/README.md)
