### ISSUE TITLE
Make a shared directory between host and docker container

### ISSUE THREAD

**Issue by n-yoshikawa** [uoft-cs-robotics/robot_system_tools#30]
It is easier to share data and codes if we have a directory that is shared between the host machine and the docker container.

**Comment by Ruthrash** [comment]
already two directories are shared between the host machine and docker container for the workstation docker. 

https://github.com/pairlab/franka_arm_infra/blob/6b031772b11330a6a257a8ac3064690dbb083c44/docker/workstation_computer/docker-compose.yml#L22 

Is this what you're referring to or something else?

**Comment by Ruthrash** [comment]
https://github.com/uoft-cs-robotics/robot_system_tools/tree/master/docker/scratchpad -> this directory in the repo is added as a placeholder for shared directory between hostmachine and workstation docker container
