### ISSUE TITLE
Calibration with D405 Troubleshooting

### ISSUE THREAD

**Issue by elishafer** [uoft-cs-robotics/robot_system_tools#34]
During calibration, I got the following error when using the D405:

```~/git/robot_toolkit# python3 robot_camera_calibration.py --config_file config/robot_camera_calibration.yaml
WARNING - 2024-01-21 13:55:35,193 - rigid_transformations - autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
INFO     [realsense_driver.py:177] Starting Intel RealSense 218622274657
ERROR    [realsense_driver.py:208] object doesn't support option #13
ERROR    [realsense_camera.py:18] Failed to start Intel RealSense 218622274657
Traceback (most recent call last):
  File "/root/git/robot_toolkit/robot_arm_algos/src/camera/realsense_driver.py", line 191, in start
    ds.set_option(rs.option.laser_power, self.laser_power)
RuntimeError: object doesn't support option #13
```

Looks like the code wants to use the laser pattern projection.
Is there any way to set the yaml file to not use the laser or perhaps set the configuration to the D405?
Btw, my setup is with an eye in hand

**Comment by Ruthrash** [comment]
If you're camera is unable to set laser power, you can comment out line 191 in robot_toolkit/robot_arm_algos/src/camera/realsense_driver.py. Also, please note the realsense camera classes are right now tested for D415 and D435. If you further face issues with the[ realsense camera](https://github.com/uoft-cs-robotics/robot_system_tools/blob/master/robot_toolkit/robot_arm_algos/src/camera/realsense_camera.py) class consider using [ros_camera](https://github.com/uoft-cs-robotics/robot_system_tools/blob/master/robot_toolkit/robot_arm_algos/src/camera/ros_camera.py) class instead

**Comment by elishafer** [comment]
Great! Thanks, commenting out line [191](https://github.com/uoft-cs-robotics/robot_system_tools/blob/ebb6b4fd4de964238b1ff9ee4e5929788029c863/robot_toolkit/robot_arm_algos/src/camera/realsense_driver.py#L191) worked
